####################################
# Dockerfile for Application image
####################################
# Base image
FROM busybox:latest
#FROM debian:jessie

# Author: MobileSnapp Inc.
MAINTAINER MobileSnapp <support@mobilesnapp.com>

# Assign working directory
WORKDIR /var/www/site

CMD ["true"]