version: '2.0'

services:

    ### Application Code ###
    data:
        build: ./data
        container_name: dockbox-data
        volumes:
            - ../:/var/www/site


    ### PHP-FPM ###
    php-fpm:
        build: ./php-fpm
        container_name: dockbox-php-fpm
        volumes:
            - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        volumes_from:
            - data
        expose:
            - "9000"
        links:
            - commons


    ### Apache ###
    apache:
        build: ./apache
        container_name: dockbox-apache
        volumes_from:
            - data
        volumes:
            - ./logs/apache/:/var/log/apache2
        ports:
            - "80:80"
            - "443:443"
        links:
            - commons


    ### Nginx ####
    nginx:
        build: ./nginx
        container_name: dockbox-nginx
        volumes_from:
            - data
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm


    ### Commons ###
    commons:
        build: ./commons
        container_name: dockbox-commons
        volumes_from:
            - data
        tty: true


    ### Redis ###
    redis:
        image: redis:alpine
        container_name: dockbox-redis
        volumes:
            - redis-data:/data
        ports:
            - "6379:6379"
        networks:
             - dockbox-net

networks:

    ### Bridged Network ###
    dockbox-net:
        driver: "bridge"

volumes:

    ### Redis Storage ###
    redis-data:
        driver: "local"