version: '2.0'

services:

### Application Code Container ###

    application:
        build: ./application
        volumes:
            - ../:/var/www/site

### Apache HTTP and PHP Container ###

    apache:
        build: ./apache
        volumes_from:
            - application
        volumes:
            - ./logs/apache/:/var/log/apache2
        ports:
            - "80:80"
            - "443:443"
        links:
             - commons

### Commons ###

    commons:
        build: ./commons
        volumes_from:
            - application
        tty: true