version: '2.0'

services:

### Application Code Container ###

    data:
        build: ./data
        container_name: dockbox-data
        volumes:
            - ../:/var/www/site
            - /volume/db:/var/lib/mysql
            - /volume/data:/data
            - /volume/memcached:/var/lib/memcached
            - /volume/mariadb:/var/lib/mariadb
            - /volume/postgres:/var/lib/postgres
            - /volume/mongo:/data/db
            - /volume/elasticsearch:/usr/share/elasticsearch/data


### PHP-FPM Container ###

    php-fpm:
        build: ./php-fpm
        container_name: dockbox-php-fpm
        volumes:
            - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        volumes_from:
            - data
        expose:
            - "9000"
        links:
            - commons


### Apache HTTP Container ###

    apache:
        build: ./apache
        container_name: dockbox-apache
        volumes_from:
            - data
        volumes:
            - ./logs/apache/:/var/log/apache2
        ports:
            - "80:80"
            - "443:443"
        links:
            - commons


### Nginx Server Container ####

    nginx:
        build: ./nginx
        container_name: dockbox-nginx
        volumes_from:
            - data
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm


### Commons ###

    commons:
        build: ./commons
        container_name: dockbox-commons
        volumes_from:
            - data
        tty: true


### Memcached ###

    memcached:
        build: ./memcached
        container_name: dockbox-memcached
        volumes_from:
            - data
        ports:
            - "11211:11211"


### Redis ###

    redis:
        build: ./redis
        container_name: dockbox-redis
        volumes_from:
            - data
        ports:
            - "6379:6379"


### MariaDB ###

    mariadb:
        build: ./mariadb
        container_name: dockbox-mariadb
        volumes_from:
            - data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: sitemariadb
            MYSQL_USER: sitedb_maria_user
            MYSQL_PASSWORD: sitedbsecret
            MYSQL_ROOT_PASSWORD: root


### PostgreSQL ###

    postgres:
        build: ./postgres
        container_name: dockbox-postgres
        volumes_from:
            - data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: sitepostgresdb
            POSTGRES_USER: sitedb_postgres_user
            POSTGRES_PASSWORD: sitedbsecret


### MySQL ###

    mysql:
        build: ./mysql
        container_name: dockbox-mysql
        volumes_from:
            - data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: sitemysqldb
            MYSQL_USER: sitedb_mysql_user
            MYSQL_PASSWORD: sitedbsecret
            MYSQL_ROOT_PASSWORD: root


### MongoDB ###

    mongodb:
        build: ./mongodb
        container_name: dockbox-mongodb
        ports:
            - "27017:27017"
        volumes_from:
            - data



### Beanstalkd ###

    beanstalkd:
        build: ./beanstalkd/queue
        container_name: dockbox-beanstalkd
        ports:
            - "11300:11300"
        privileged: true
        links:
            - commons



### Beanstalkd Console ###

    beanstalkd-console:
        build: ./beanstalkd/console
        container_name: dockbox-beanstalkd-console
        ports:
            - "2080:2080"
        links:
            - beanstalkd



### RabbitMQ ###

    rabbitmq:
        build: ./rabbitmq
        container_name: dockbox-rabbitmq
        volumes_from:
            - data
        ports:
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "15672:15672"
            - "25672:25672"


### Elasticsearch ###

    elasticsearch:
        build: ./elasticsearch
        container_name: dockbox-elasticsearch
        volumes_from:
            - data
        ports:
            - "9200:9200"
            - "9300:9300"
