##################################
# Dockerfile for Memcached image
##################################
# Base image
FROM memcached:latest

# Author: MobileSnapp Inc.
MAINTAINER MobileSnapp <support@mobilesnapp.com>

# Expose port
EXPOSE 11211

CMD ["memcached"]

