##########################################
# Dockerfile to build Elasticsearch image
##########################################
# Base image
FROM elasticsearch:alpine

# Author: MobileSnapp Inc.
MAINTAINER Bo-Yi Wu <appleboy.tw@gmail.com>

# Expose ports.
EXPOSE 9200 9300