##########################################
# Dockerfile to build Elasticsearch image
##########################################
# Base image
FROM elasticsearch

# Author: MobileSnapp Inc.
MAINTAINER MobileSnapp <support@mobilesnapp.com>

# Expose ports.
EXPOSE 9200 9300