################################
# Dockerfile for MariaDB image
################################
# Base image
FROM mariadb:latest

# Author: MobileSnapp Inc.
MAINTAINER MobileSnapp <support@mobilesnapp.com>

# Expose port
EXPOSE 3306

CMD ["mysqld"]