####################################
# Dockerfile for Data volume image
####################################
# Base image
FROM busybox:latest

# Author: MobileSnapp Inc.
MAINTAINER MobileSnapp <support@mobilesnapp.com>

# Assign working directory
WORKDIR /var/www/site

CMD ["true"]