################################
# Dockerfile for MySQL image
################################
# Base image
FROM mysql:latest

# Author: MobileSnapp Inc.
MAINTAINER MobileSnapp <support@mobilesnapp.com>

# Expose port
EXPOSE 3306

CMD ["mysqld"]