##################################
# Dockerfile for Postgres image
##################################
# Base image
FROM postgres:latest

# Author: MobileSnapp Inc.
MAINTAINER MobileSnapp <support@mobilesnapp.com>

# Expose port
EXPOSE 5432

CMD ["postgres"]