################################
# Dockerfile for MariaDB image
################################
# Base image
FROM redis:latest

# Author: MobileSnapp Inc.
MAINTAINER MobileSnapp <support@mobilesnapp.com>

VOLUME /data

# Expose port
EXPOSE 6379

CMD ["redis-server"]